### ISSUE TITLE
Error testing TiffBitmapFactory

### ISSUE THREAD

**Issue by iguron** [Beyka/Android-TiffBitmapFactory#12]
Hi Aleksey,

First of all, thanks for the effort Implementing on version 0.9.6 Group 4 compression.

I have a problem, but I guess it is not related to this version (as it happens also on 0.9.5 for me). Testing TiffBitmapFactory on the emulator works fine but when I try to do it in the mobile, i get an error during saveBitmap in the line  System.loadLibrary("tiff")

The mobile is an Android 6.0 MTK6580 Quad-Core

any help? Please...

**Comment by Beyka** [comment]
Did you use built version with gradle or built your own version from sources?
Also is problem only on MTK6580 Quad-Core or on any other platform?
Also please extract files from your apk and check that there is "lib" folder.  In lib folder please check folder "armeabi-v7a". There is should be 3 files: libtiff.so, libtifffactory.so libtiffsaver.so.

**Comment by iguron** [comment]
Thanks for the quick answer. answering your questions:

Directly with gradle.
I have no other device to check.
I check inside the apk, and yes there is a folder armeabi-v7a and yes these three libs on it.

**Comment by iguron** [comment]
I tried in a "clean" project, in order to see that there is no collateral problem and it fails also.

BTW. I assume that this is not connected but...

In your example to save a TIFF these lines:

options.compressionMode = TiffSaver.CompressionMode.COMPRESSION_LZW;
//By default orientation is top left
options.orientation = TiffSaver.Orientation.ORIENTATION_LEFTTOP;

I need to change them to:

options.compressionScheme = CompressionScheme.COMPRESSION_LZW;
			//By default orientation is top left
			options.orientation = Orientation.ORIENTATION_TOPLEFT;

**Comment by iguron** [comment]
Maybe this is the problem?

[http://stackoverflow.com/a/16208717](url)

**Comment by iguron** [comment]
This is the exact error.
 cannot locate symbol "__aeabi_memset" referenced by "/data/app/com.example.android.photobyintent-2/lib/arm/libtiff.so"

**Comment by Beyka** [comment]
What targetSdkVersion you are using? Alos do you use proguard?

As for compression and orientation I didn't understand question. You can use any compression scheme with any orientation

**Comment by iguron** [comment]
I´m quiet new on Android programming, so Proguard files are present on the project. Should I remove it?

targetSdkVersion 25, should I go lower?

About orientation and compression, I mean that the example you put on the main screen in github is not correct.

**Comment by iguron** [comment]
I have tested the apk in other device (amazon tablet) and it works. It is just on this particular device armeabi-v7a

**Comment by Beyka** [comment]
I will check sample in readme file.
As for your problem, please try to set target SDK to 23.

**Comment by iguron** [comment]
Setting target to 23 doesn´t work. What do you mean with "add for matk"?

**Comment by Beyka** [comment]
Could you provide full stack trace of error?

**Comment by iguron** [comment]
Hi,

Here you have. Same error on target 23 or 25. 

03-09 21:53:54.697 10819-10819/com.example.android.photobyintent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.example.android.photobyintent, PID: 10819
                                                                                   java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memset" referenced by "/data/app/com.example.android.photobyintent-1/lib/arm/libtiff.so"...
                                                                                       at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                                                       at org.beyka.tiffbitmapfactory.TiffSaver.<clinit>(TiffSaver.java:16)
                                                                                       at org.beyka.tiffbitmapfactory.TiffSaver.saveBitmap(TiffSaver.java)
                                                                                       at com.example.android.photobyintent.PhotoIntentActivity.handleBigCameraPhoto(PhotoIntentActivity.java:228)
                                                                                       at com.example.android.photobyintent.PhotoIntentActivity.onActivityResult(PhotoIntentActivity.java:334)
                                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:6500)
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3925)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3972)
                                                                                       at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by iguron** [comment]
BTW. Just to remove collateral issues, I download the example of camera from Android developer web and add your code "as is" for saving as TiF. In the emulator, it works and in the mobile it doesn´t

**Comment by Beyka** [comment]
I can't check now - will be at computer in a hour, but could you try target SDK 22 or less? Thank you)

**Comment by Beyka** [comment]
Here what quick search gave to me
http://stackoverflow.com/a/32851814/2092850

**Comment by iguron** [comment]
Same error on 22. I guess that the problem is not in my side, but on TiffFactory as "you" are the user of the libary TiFF. Maybe you should build the TiffBitmapFactory with the version 22 and also check this solution in the same answer you gave me.

[http://stackoverflow.com/a/41022492/7569288](url)

**Comment by Beyka** [comment]
Could you please try to use this build of lib?
compile 'com.github.beyka:androidtiffbitmapfactory:0.9.6.1'

**Comment by iguron** [comment]
Sorry, same error...

**Comment by Beyka** [comment]
Try please this two builds
compile 'com.github.beyka:androidtiffbitmapfactory:0.9.6.1-b10d'
compile 'com.github.beyka:androidtiffbitmapfactory:0.9.6.1-b14'
BTW. This error apear only when you trying to use TiffSaver or also when you use TiffBitmapFactory?

**Comment by iguron** [comment]
Hi Aleksey,

After a quick testing...
b10d works!!!
and b14 it doesn´t. But as I said let me test it deeper.

To your question I will say that the crash always happens on TiffSaver, when you try to lad the lib Tiff (I didn´t test other part of your code).

Let me make some testings...

BTW. Do you know how to give different resolutions to the tiff file, now it is always 100dpi.

Thanks!!!!

**Comment by Beyka** [comment]
If b10d works, it's mean that problem in Android ndk . I will rebuild l library.
As for DPI, 100 DPI for any compression scheme of only for group 3 and 4?

**Comment by iguron** [comment]
DPI  (resolution) of the image is really important. We should be able to choose the DPI of the image. For any compression scheme.

**Comment by Beyka** [comment]
> DPI (resolution) of the image is really important. We should be able to choose the DPI of the image. For any compression scheme.

I Can add support for tiff tags TIFFTAG_XRESOLUTION, TIFFTAG_YRESOLUTION and TIFFTAG_RESOLUTIONUNIT, but here what libtiff documentations says:

>  The number of pixels per ResolutionUnit in the ImageWidth direction.
> It is not mandatory that the image be actually displayed or printed at the size implied by this parameter. It is up to the application to use this information as it wishes. 

So I will add this fields in nearest release of library, but I don't know how it will work

**Comment by iguron** [comment]
Yes, these are the parameters you need for resolution. 

.. and documentation is OK, for printing or displaying, it depends on the monitor, or the printer, no the image resolution itself.

But believe me anyone that needs group 4, needs to set the resolution.

Thanks in advance!!

**Comment by Beyka** [comment]
Added in build 0.9.6.2

**Comment by kirantpatil** [comment]
Hi @Beyka,

Could you please share an example of how to set DPI ?

Thanks.
