### ISSUE TITLE
the error log is "JNI GetStaticObjectField called with pending exception 'java.lang.NoSuchFieldError' thrown in boolean "

### ISSUE THREAD

**Issue by 1049884729** [Beyka/Android-TiffBitmapFactory#17]
I have a question when I used the old demo; error log is 
`05-05 13:40:04.798 15173-15362/JNI DETECTED ERROR IN APPLICATION: JNI GetStaticObjectField called with pending exception 'java.lang.NoSuchFieldError' thrown in boolean org.beyka.tiffbitmapfactory.TiffSaver.save(java.lang.String, android.graphics.Bitmap, org.beyka.tiffbitmapfactory.TiffSaver$SaveOptions, boolean):-2
   in call to GetStaticObjectField
   from boolean org.beyka.tiffbitmapfactory.TiffSaver.save(java.lang.String, android.graphics.Bitmap, org.beyka.tiffbitmapfactory.TiffSaver$SaveOptions, boolean)
05-05 13:40:04.798 15173-15362/"AsyncTask #1" prio=5 tid=56 Runnable
 | group="main" sCount=0 dsCount=0 obj=0x12c06ca0 self=0xdcc46000
 | sysTid=15362 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xe2448000
 | state=R schedstat=( 57966230 15888615 136 ) utm=5 stm=0 core=0 HZ=100
 | stack=0xdd9f7000-0xdd9f9000 stackSize=1036KB
 | held mutexes= "mutator lock"(shared held)
 native: #00 pc 0000505c  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
 native: #01 pc 00003739  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
 native: #02 pc 0024a6e9  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
 native: #03 pc 0022e7e1  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+148)
 native: #04 pc 000b0d0f  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
 native: #05 pc 000b144f  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+58)
 native: #06 pc 000b4549  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1284)
 native: #07 pc 000b68c9  /system/lib/libart.so (art::CheckJNI::GetStaticObjectField(_JNIEnv*, _jclass*, _jfieldID*)+40)
 native: #08 pc 00001f13  /data/app/com.test.demo-1/lib/arm/libtiffsaver.so (Java_org_beyka_tiffbitmapfactory_TiffSaver_save+1186)
 native: #09 pc 00001eab  /data/dalvik-cache/arm/data@app@com.test.demo-1@base.apk@classes.dex (Java_org_beyka_tiffbitmapfactory_TiffSaver_save__Ljava_lang_String_2Landroid_graphics_Bitmap_2Lorg_beyka_tiffbitmapfactory_TiffSaver_00024SaveOptions_2Z+174)
 at org.beyka.tiffbitmapfactory.TiffSaver.save(Native method)
 - locked <0x1f5ae728> (a java.lang.Class<org.beyka.tiffbitmapfactory.TiffSaver>)
 at org.beyka.tiffbitmapfactory.TiffSaver.appendBitmap(TiffSaver.java:139)
 at org.beyka.tiffbitmapfactory.TiffSaver.appendBitmap(TiffSaver.java:107)`

Thanks sir!

**Comment by Beyka** [comment]
Hello! What you mean under "old demo" and could you provide some code where you create SaveOptions and call TiffSaver?

**Comment by 1049884729** [comment]
when I used " compile 'com.github.beyka:androidtiffbitmapfactory:0.9.6.1-b10d'",the compile is success and      all operations is ok.But when I used " compile 'com.github.beyka:androidtiffbitmapfactory:0.9.7'" , the above  error happened

**Comment by Beyka** [comment]
There are many changes in API since version 0.9.6.1. ALso latest version is 0.9.7.3.
So try latest version of library nad if it not helps you, please provide some code.
Thank you
